import { expect } from 'chai';
/* eslint-disable @typescript-eslint/no-explicit-any */
import * as fc from 'fast-check';
import { Database } from '../src/core/database.js';
import { compareSqlValues } from '../src/util/comparison.js';
import { safeJsonStringify } from '../src/util/serialization.js';
import type { Row, SqlValue } from '../src/common/types.js';
import { Parser } from '../src/parser/parser.js';
import { QuereusError } from '../src/common/errors.js';
import { assertTableSchemaEqual, assertProbeEquivalent } from './util/schema-equivalence.js';
import { keysOf, isUnique } from '../src/planner/util/fd-utils.js';
import { deriveViewColumns } from '../src/planner/analysis/update-lineage.js';
import type * as AST from '../src/parser/ast.js';
import { type PlanNode, type RelationalPlanNode, isRelationalNode } from '../src/planner/nodes/plan-node.js';
import { EmissionContext } from '../src/runtime/emission-context.js';
import { emitPlanNode } from '../src/runtime/emitters.js';
import { Scheduler } from '../src/runtime/scheduler.js';
import { createStrictRowContextMap, wrapTableContextsStrict } from '../src/runtime/strict-fork.js';
import { isAsyncIterable } from '../src/runtime/utils.js';
import type { RuntimeContext } from '../src/runtime/types.js';

describe('Property-Based Tests', () => {
	let db: Database;

	beforeEach(() => {
		db = new Database();
		// Ensure collations are registered (already done in Database constructor)
	});

	afterEach(async () => {
		await db.close();
	});

	/**
	 * Deep equality comparison that treats -0 and +0 as equal,
	 * since JSON cannot preserve the distinction between them.
	 */
	function deepEqualIgnoringZeroSign(actual: any, expected: any): boolean {
		if (actual === expected) return true;

		// Handle the -0 vs +0 case
		if (typeof actual === 'number' && typeof expected === 'number' &&
			actual === 0 && expected === 0) {
			return true; // Treat -0 and +0 as equal
		}

		// Handle arrays
		if (Array.isArray(actual) && Array.isArray(expected)) {
			if (actual.length !== expected.length) return false;
			for (let i = 0; i < actual.length; i++) {
				if (!deepEqualIgnoringZeroSign(actual[i], expected[i])) return false;
			}
			return true;
		}

		// Handle objects
		if (actual !== null && expected !== null &&
			typeof actual === 'object' && typeof expected === 'object') {
			const actualKeys = Object.keys(actual);
			const expectedKeys = Object.keys(expected);
			if (actualKeys.length !== expectedKeys.length) return false;

			for (const key of actualKeys) {
				if (!expectedKeys.includes(key)) return false;
				if (!deepEqualIgnoringZeroSign(actual[key], expected[key])) return false;
			}
			return true;
		}

		return false;
	}

	// --- 1. Collation Comparator ---
	describe('Collation Comparator', () => {
		const collationsToTest = ['BINARY', 'NOCASE', 'RTRIM'];

		for (const collationName of collationsToTest) {
			it(`should sort consistently with compare function for ${collationName} collation`, async () => {
				await db.exec(`CREATE TABLE coll_t (id INTEGER PRIMARY KEY, txt TEXT COLLATE ${collationName}) USING memory`);

				await fc.assert(fc.asyncProperty(fc.array(fc.string(), { minLength: 1, maxLength: 20 }), async (strings) => {
					// Use a Map to handle potential duplicate strings generated by fast-check, preserving insertion order for comparison
					const uniqueStringsMap = new Map<string, boolean>();
					strings.forEach(s => uniqueStringsMap.set(s, true));
					const uniqueStrings = Array.from(uniqueStringsMap.keys());

					// Reset table for each property run
					await db.exec('DELETE FROM coll_t');
					const stmt = db.prepare('INSERT INTO coll_t (id, txt) VALUES (?, ?)');
					try {
						for (let i = 0; i < uniqueStrings.length; i++) {
							await stmt.run([i + 1, uniqueStrings[i]]);
						}
					} finally {
						await stmt.finalize();
					}

					// Get sorted results from the database
					const dbSorted: Record<string, any>[] = [];
					for await (const row of db.eval(`SELECT txt FROM coll_t ORDER BY txt`)) {
						dbSorted.push(row);
					}
					const dbSortedStrings = dbSorted.map((row: Record<string, any>) => row.txt as string);

					// Sort the original unique strings using the JavaScript compare function
					const jsSortedStrings = [...uniqueStrings].sort((a, b) => compareSqlValues(a, b, collationName));

					// Compare the two sorted lists
					expect(dbSortedStrings).to.deep.equal(jsSortedStrings, `Mismatch for collation ${collationName} with input: ${safeJsonStringify(uniqueStrings)}`);
				}), { numRuns: 50 }); // Keep numRuns reasonable for CI
			});
		}
	});

	// --- 2. Numeric Affinity ---
	describe('Numeric Affinity', () => {
		// Define an arbitrary that generates values representable as NULL, INTEGER, REAL, or TEXT that might look numeric
		const sqlValueArbitrary = fc.oneof(
			fc.constant(null),
			fc.integer(),
			fc.float({ noNaN: true }), // Exclude NaN as it complicates SQL comparisons
			fc.boolean(),
			fc.string(), // Includes numeric-looking strings
			fc.bigInt()
			// fc.uint8Array() // Skip BLOBs for numeric affinity tests
		);

		it('should compare values according to numeric affinity', async () => {
			await db.exec('CREATE TABLE num_t (id INTEGER PRIMARY KEY, v ANY null) USING memory'); // Use ANY type (has NUMERIC affinity)

			await fc.assert(fc.asyncProperty(sqlValueArbitrary, sqlValueArbitrary, async (valA, valB) => {
				// Insert values and let SQL apply type affinity conversion
				await db.exec('DELETE FROM num_t');
				// Don't reuse prepared statements - parameter types may differ between runs
				const stmt1 = db.prepare('INSERT INTO num_t (id, v) VALUES (?, ?)');
				try {
					await stmt1.run([1, valA]);
				} finally {
					await stmt1.finalize();
				}
				const stmt2 = db.prepare('INSERT INTO num_t (id, v) VALUES (?, ?)');
				try {
					await stmt2.run([2, valB]);
				} finally {
					await stmt2.finalize();
				}

				// Retrieve the actual values after type affinity conversion
				const actualValues: SqlValue[] = [];
				for await (const row of db.eval('SELECT v FROM num_t ORDER BY id')) {
					actualValues.push(row.v);
				}
				const [actualA, actualB] = actualValues;

				// For ORDER BY, we use compareSqlValues directly (no coercion)
				// ORDER BY uses storage class ordering: NULL < NUMERIC < TEXT < BLOB
				const expectedOrderByComparison = compareSqlValues(actualA, actualB, 'BINARY');

				// Test ordering behavior using ORDER BY
				const orderedValues: SqlValue[] = [];
				for await (const row of db.eval('SELECT v FROM num_t ORDER BY v')) {
					orderedValues.push(row.v);
				}

				// Check if the ordering matches our expectation based on storage class ordering
				if (expectedOrderByComparison < 0) {
					expect(orderedValues).to.deep.equal([actualA, actualB],
						`ORDER BY should place ${safeJsonStringify(actualA)} before ${safeJsonStringify(actualB)}`);
				} else if (expectedOrderByComparison > 0) {
					expect(orderedValues).to.deep.equal([actualB, actualA],
						`ORDER BY should place ${safeJsonStringify(actualB)} before ${safeJsonStringify(actualA)}`);
				} else {
					// Equal values - order doesn't matter, but both should be present
					expect(orderedValues).to.have.lengthOf(2);
					expect(orderedValues).to.include(actualA);
					expect(orderedValues).to.include(actualB);
				}

				// For non-NULL values, also test SQL boolean comparisons
				// SELECT ? = ? uses storage class ordering (no column affinity coercion)
				// NULL < INTEGER/REAL < TEXT < BLOB
				if (actualA !== null && actualB !== null) {
					const expectedComparison = compareSqlValues(actualA, actualB, 'BINARY');

					let dbComparison: number;
					try {
						// Check A = B using eval and taking the first row
						let eqResult: Record<string, any> | undefined;
						for await (const row of db.eval('SELECT ? = ? as result', [actualA, actualB])) {
							eqResult = row;
							break; // Only need the first (and only) row
						}
						if (eqResult?.result) {
							dbComparison = 0;
						} else {
							// Check A < B using eval and taking the first row
							let ltResult: Record<string, any> | undefined;
							for await (const row of db.eval('SELECT ? < ? as result', [actualA, actualB])) {
								ltResult = row;
								break; // Only need the first row
							}
							dbComparison = ltResult?.result ? -1 : 1;
						}
					} catch (e: any) {
						// If the comparison itself throws an error in SQL, fail the property test
						fc.pre(false); // Discard this run if SQL comparison fails
						throw new Error(`SQL comparison failed for (${actualA}, ${actualB}): ${e.message}`);
					}

					expect(dbComparison).to.equal(expectedComparison,
						`Mismatch for compare(${safeJsonStringify(actualA)}, ${safeJsonStringify(actualB)}). JS=${expectedComparison}, DB=${dbComparison}`
					);
				}
			}), { numRuns: 200 }); // Increase runs for more diverse value pairs
		});
	});

	// --- 3. JSON Roundtrip ---
	describe('JSON Roundtrip', () => {
		const jsonValueArbitrary = fc.jsonValue();

		it('should preserve JSON values through json() and json_extract()', async () => {
			await fc.assert(fc.asyncProperty(jsonValueArbitrary, async (originalValue) => {
				let retrievedValueParsed: any;
				try {
					let resultRow: Record<string, any> | undefined;
					for await (const row of db.eval("SELECT json_extract(json_quote(?), '$') as result", [originalValue as SqlValue])) {
						resultRow = row;
						break; // We only expect one row from this SELECT
					}

					if (resultRow) {
						retrievedValueParsed = resultRow.result;
					} else {
						// This case should ideally not be hit if originalValue is valid for json_quote
						// and json_extract can process it. If it is, it might indicate an issue
						// with how null/empty results are handled by db.eval or the underlying functions.
						// For certain inputs like trying to json_quote a function or symbol (which fc.jsonValue should not produce),
						// an error might occur during SQL execution, caught by the outer catch block.
						// If the query legitimately returns no rows (e.g. SELECT FROM empty_table), this branch would be hit.
						// But SELECT json_extract(...) should always return one row.
						throw new Error('json_extract query returned no result row unexpectedly.');
					}
				} catch (e: any) {
					fc.pre(false); // Discard this run if SQL execution fails
					throw new Error(`JSON roundtrip query failed for value ${safeJsonStringify(originalValue)}: ${e.message}`);
				}

				// Handle the different ways json_extract returns values based on SQLite compatibility:
				// - Objects/arrays: returned as JSON strings
				// - Booleans: converted to integers (1/0)
				// - Numbers/strings/null: returned as-is

				if (typeof retrievedValueParsed === 'string' && (typeof originalValue === 'object' && originalValue !== null)) {
					// Objects and arrays are returned as JSON strings - parse them for comparison
					try {
						const parsedRetrieved = JSON.parse(retrievedValueParsed);
						const isEqual = deepEqualIgnoringZeroSign(parsedRetrieved, originalValue);
						void expect(isEqual,
							`JSON roundtrip mismatch after parsing string result.\nOriginal: ${safeJsonStringify(originalValue)}\nRetrieved (raw): ${safeJsonStringify(retrievedValueParsed)}\nRetrieved (parsed): ${safeJsonStringify(parsedRetrieved)}`
						).to.be.true;
					} catch (parseError) {
						throw new Error(`JSON roundtrip failed - could not parse retrieved string.\nOriginal: ${safeJsonStringify(originalValue)}\nRetrieved: ${safeJsonStringify(retrievedValueParsed)}\nParse error: ${parseError instanceof Error ? parseError.message : String(parseError)}`);
					}
				} else if (typeof originalValue === 'boolean' && typeof retrievedValueParsed === 'number') {
					// Booleans are converted to integers by json_extract (SQLite compatibility)
					const expectedInteger = originalValue ? 1 : 0;
					void expect(retrievedValueParsed).to.equal(expectedInteger,
						`JSON boolean roundtrip mismatch.\nOriginal boolean: ${originalValue}\nExpected integer: ${expectedInteger}\nRetrieved: ${retrievedValueParsed}`
					);
				} else {
					// For other scalars (numbers, strings, null), use zero-sign-aware comparison
					const isEqual = deepEqualIgnoringZeroSign(retrievedValueParsed, originalValue);
					void expect(isEqual,
						`JSON roundtrip mismatch.\nOriginal: ${safeJsonStringify(originalValue)} (type: ${typeof originalValue})\nRetrieved: ${safeJsonStringify(retrievedValueParsed)} (type: ${typeof retrievedValueParsed})`
					).to.be.true;
				}
			}), { numRuns: 200 });
		});

		it('should handle JSON edge values through json_extract', async () => {
			// Deeply nested object (12 levels)
			let deepObj: any = { value: 42 };
			for (let i = 0; i < 12; i++) {
				deepObj = { nested: deepObj };
			}

			// Large array (1000 elements)
			const largeArray = Array.from({ length: 1000 }, (_, i) => i);

			// Object with empty-string key
			const emptyKeyObj = { '': 'empty-key-value', 'normal': 'value' };

			// Mixed-type values in one object
			const mixedObj = {
				str: 'hello',
				num: 42,
				float: 3.14,
				bool: true,
				nil: null,
				arr: [1, 'two', null, false],
				obj: { a: 1 },
			};

			const edgeCases: Array<{ label: string; value: any }> = [
				{ label: 'deeply nested object', value: deepObj },
				{ label: 'large array (1000 elements)', value: largeArray },
				{ label: 'empty-string key object', value: emptyKeyObj },
				{ label: 'mixed-type object', value: mixedObj },
				{ label: 'empty object', value: {} },
				{ label: 'empty array', value: [] },
				{ label: 'nested arrays', value: [[1, 2], [3, [4, 5]]] },
			];

			for (const { label, value } of edgeCases) {
				const jsonStr = JSON.stringify(value);
				let resultRow: Record<string, any> | undefined;
				for await (const row of db.eval("select json_extract(?, '$') as result", [jsonStr])) {
					resultRow = row;
					break;
				}

				expect(resultRow).to.not.be.undefined;
				// json_extract returns objects/arrays as JSON strings
				const parsed = typeof resultRow!.result === 'string'
					? JSON.parse(resultRow!.result)
					: resultRow!.result;
				const isEqual = deepEqualIgnoringZeroSign(parsed, value);
				expect(isEqual, `JSON edge roundtrip failed for ${label}`).to.be.true;
			}
		});
	});

	// --- 4. Mixed Type Arithmetic Edge Cases ---
	describe('Mixed Type Arithmetic Edge Cases', () => {
		const complexValueArbitrary = fc.oneof(
			fc.constant(null),
			fc.integer({ min: -1000, max: 1000 }),
			fc.float({ min: -1000, max: 1000, noNaN: true }),
			fc.boolean(),
			fc.oneof(
				fc.string({ minLength: 0, maxLength: 5 }),
				fc.integer().map(n => n.toString()),
				fc.float().map(n => n.toString()),
				fc.constant(''),
				fc.constant('0'),
				fc.constant('1'),
				fc.constant('true'),
				fc.constant('false')
			)
		);

		it('should handle mixed type arithmetic consistently across contexts', async () => {
			await db.exec('CREATE TABLE mixed_test (id INTEGER PRIMARY KEY, a ANY null, b ANY null) USING memory');

			await fc.assert(fc.asyncProperty(complexValueArbitrary, complexValueArbitrary, async (valA, valB) => {
				// Clear table and insert test values
				await db.exec('DELETE FROM mixed_test');
				const stmt = db.prepare('INSERT INTO mixed_test (id, a, b) VALUES (?, ?, ?)');
				try {
					await stmt.run([1, valA, valB]);
				} finally {
					await stmt.finalize();
				}

				// Test arithmetic in different contexts - they should all produce the same result or all fail
				let selectResult: any = undefined;
				let selectFailed = false;
				let whereResult: any = undefined;
				let whereFailed = false;

				// Test in SELECT
				try {
					for await (const row of db.eval('SELECT (a + b) as result FROM mixed_test')) {
						selectResult = row.result;
						break;
					}
				} catch {
					selectFailed = true;
				}

				// Test in WHERE (using a comparison to ensure arithmetic works)
				try {
					for await (const row of db.eval('SELECT (a + b) as result FROM mixed_test WHERE (a + b) = (a + b)')) {
						whereResult = row.result;
						break;
					}
				} catch {
					whereFailed = true;
				}

				// Both should succeed or both should fail
				expect(selectFailed).to.equal(whereFailed,
					`Arithmetic behavior inconsistent between SELECT and WHERE for (${safeJsonStringify(valA)}, ${safeJsonStringify(valB)})`);

				// If both succeeded, results should match
				// Note: if selectResult is null, whereResult might be undefined (no rows returned)
				// This is expected behavior when the result is null
				if (!selectFailed && !whereFailed) {
					if (selectResult === null) {
						// If SELECT returns null, WHERE with self-comparison should return no rows (undefined)
						// This is actually correct behavior - NULL != NULL in SQL
						void expect(whereResult).to.be.undefined;
					} else {
						// For non-null results, they should match exactly
						expect(selectResult).to.equal(whereResult,
							`Arithmetic results differ between SELECT and WHERE for (${safeJsonStringify(valA)}, ${safeJsonStringify(valB)})`);
					}
				}
			}), { numRuns: 100 });
		});
	});

	// --- 5. Parser Robustness ---
	describe('Parser Robustness', () => {
		it('should never throw unhandled exceptions on random input', () => {
			const parser = new Parser();

			fc.assert(fc.property(fc.string({ minLength: 0, maxLength: 200 }), (input) => {
				try {
					parser.parseAll(input);
				} catch (e) {
					if (!(e instanceof QuereusError)) {
						throw new Error(`Parser threw non-QuereusError on input ${safeJsonStringify(input)}: ${e}`);
					}
				}
			}), { numRuns: 200 });
		});

		it('should handle SQL-like fragments mixed with garbage', () => {
			const parser = new Parser();
			const sqlFragments = fc.oneof(
				fc.constant('select'),
				fc.constant('from'),
				fc.constant('where'),
				fc.constant('insert'),
				fc.constant('into'),
				fc.constant('values'),
				fc.constant('update'),
				fc.constant('delete'),
				fc.constant('create'),
				fc.constant('table'),
				fc.constant('drop'),
				fc.constant('alter'),
				fc.constant('join'),
				fc.constant('on'),
				fc.constant('group by'),
				fc.constant('order by'),
				fc.constant('having'),
				fc.constant('limit'),
				fc.constant('('),
				fc.constant(')'),
				fc.constant(','),
				fc.constant(';'),
				fc.constant('*'),
				fc.constant('='),
				fc.constant('and'),
				fc.constant('or'),
				fc.constant('not'),
				fc.string({ minLength: 1, maxLength: 10 })
			);

			fc.assert(fc.property(fc.array(sqlFragments, { minLength: 1, maxLength: 15 }), (fragments) => {
				const input = fragments.join(' ');
				try {
					parser.parseAll(input);
				} catch (e) {
					if (!(e instanceof QuereusError)) {
						throw new Error(`Parser threw non-QuereusError on SQL fragment input: ${e}`);
					}
				}
			}), { numRuns: 200 });
		});

		it('should handle random identifiers in SELECT statements gracefully', () => {
			const parser = new Parser();
			const identArbitrary = fc.oneof(
				fc.stringMatching(/^[a-zA-Z_][a-zA-Z0-9_]{0,20}$/),
				// Bracket-quoted identifiers
				fc.string({ minLength: 1, maxLength: 20 }).map(s => `[${s.replace(/]/g, ']]')}]`),
				// Double-quote identifiers
				fc.string({ minLength: 1, maxLength: 20 }).map(s => `"${s.replace(/"/g, '""')}"`),
				// Backtick identifiers
				fc.string({ minLength: 1, maxLength: 20 }).map(s => '`' + s.replace(/`/g, '``') + '`'),
				// Reserved words used as identifiers
				fc.constantFrom('select', 'from', 'where', 'table', 'index', 'order', 'group', 'having', 'limit', 'null', 'true', 'false')
			);

			fc.assert(fc.property(identArbitrary, (ident) => {
				const sql = `select ${ident} from t`;
				try {
					parser.parseAll(sql);
				} catch (e) {
					if (!(e instanceof QuereusError)) {
						throw new Error(`Parser threw non-QuereusError on identifier ${safeJsonStringify(ident)}: ${e}`);
					}
				}
			}), { numRuns: 200 });
		});
	});

	// --- 6. Expression Evaluation Consistency ---
	describe('Expression Evaluation Consistency', () => {
		// Build random arithmetic expression trees
		const literalArb = fc.integer({ min: -100, max: 100 });
		const opArb = fc.constantFrom('+', '-', '*');

		// Generate expression as [sqlString, jsValue] pairs
		// Avoid division to keep things simple (division-by-zero, integer vs float semantics)
		// Negative literals are wrapped in parens so the parser doesn't see e.g. `* -1`
		function litToSql(n: number): string {
			return n < 0 ? `(${n})` : String(n);
		}

		function exprArbitrary(depth: number): fc.Arbitrary<{ sql: string; value: number }> {
			if (depth <= 0) {
				return literalArb.map(n => ({ sql: litToSql(n), value: n }));
			}
			return fc.oneof(
				literalArb.map(n => ({ sql: litToSql(n), value: n })),
				fc.tuple(exprArbitrary(depth - 1), opArb, exprArbitrary(depth - 1)).map(([left, op, right]) => {
					let value: number;
					switch (op) {
						case '+': value = left.value + right.value; break;
						case '-': value = left.value - right.value; break;
						case '*': value = left.value * right.value; break;
						default: value = left.value + right.value;
					}
					return { sql: `(${left.sql} ${op} ${right.sql})`, value };
				})
			);
		}

		it('should evaluate arithmetic expressions consistently with JS', async () => {
			await fc.assert(fc.asyncProperty(exprArbitrary(3), async (expr) => {
				// Skip expressions that would overflow JS safe integers
				fc.pre(Math.abs(expr.value) < Number.MAX_SAFE_INTEGER);

				let result: any;
				for await (const row of db.eval(`select ${expr.sql} as r`)) {
					result = row.r;
					break;
				}

				expect(result).to.equal(expr.value,
					`Mismatch for expression: ${expr.sql}, expected ${expr.value}, got ${result}`);
			}), { numRuns: 200 });
		});

		it('should evaluate boolean comparison expressions consistently', async () => {
			const compOp = fc.constantFrom('=', '!=', '<', '>', '<=', '>=');

			await fc.assert(fc.asyncProperty(literalArb, compOp, literalArb, async (a, op, b) => {
				let jsResult: boolean;
				switch (op) {
					case '=': jsResult = a === b; break;
					case '!=': jsResult = a !== b; break;
					case '<': jsResult = a < b; break;
					case '>': jsResult = a > b; break;
					case '<=': jsResult = a <= b; break;
					case '>=': jsResult = a >= b; break;
					default: jsResult = false;
				}

				let sqlResult: any;
				for await (const row of db.eval(`select (${litToSql(a)} ${op} ${litToSql(b)}) as r`)) {
					sqlResult = row.r;
					break;
				}

				// SQL may return boolean true/false or 1/0
				const sqlBool = sqlResult === true || sqlResult === 1;
				expect(sqlBool).to.equal(jsResult,
					`Mismatch for ${a} ${op} ${b}: SQL=${sqlResult}, JS=${jsResult}`);
			}), { numRuns: 200 });
		});
	});

	// --- 7. Comparison Transitivity and Antisymmetry ---
	describe('Comparison Properties', () => {
		const mixedValueArb = fc.oneof(
			fc.constant(null as SqlValue),
			fc.integer({ min: -1000, max: 1000 }) as fc.Arbitrary<SqlValue>,
			fc.float({ min: -1000, max: 1000, noNaN: true, noDefaultInfinity: true }) as fc.Arbitrary<SqlValue>,
			fc.string({ minLength: 0, maxLength: 10 }) as fc.Arbitrary<SqlValue>,
			fc.boolean() as fc.Arbitrary<SqlValue>
		);

		it('should maintain antisymmetry: compare(a,b) === -compare(b,a)', () => {
			fc.assert(fc.property(mixedValueArb, mixedValueArb, (a, b) => {
				const ab = compareSqlValues(a, b);
				const ba = compareSqlValues(b, a);
				expect(Math.sign(ab)).to.equal(-Math.sign(ba),
					`Antisymmetry violated: compare(${safeJsonStringify(a)}, ${safeJsonStringify(b)})=${ab}, compare(${safeJsonStringify(b)}, ${safeJsonStringify(a)})=${ba}`);
			}), { numRuns: 200 });
		});

		it('should maintain reflexivity: compare(a,a) === 0', () => {
			fc.assert(fc.property(mixedValueArb, (a) => {
				expect(compareSqlValues(a, a)).to.equal(0,
					`Reflexivity violated for ${safeJsonStringify(a)}`);
			}), { numRuns: 200 });
		});

		it('should maintain transitivity: if a<=b and b<=c then a<=c', () => {
			fc.assert(fc.property(mixedValueArb, mixedValueArb, mixedValueArb, (a, b, c) => {
				const ab = compareSqlValues(a, b);
				const bc = compareSqlValues(b, c);
				const ac = compareSqlValues(a, c);

				if (ab <= 0 && bc <= 0) {
					expect(ac).to.be.at.most(0,
						`Transitivity violated: ${safeJsonStringify(a)} <= ${safeJsonStringify(b)} <= ${safeJsonStringify(c)}, but compare(a,c)=${ac}`);
				}
				if (ab >= 0 && bc >= 0) {
					expect(ac).to.be.at.least(0,
						`Transitivity violated: ${safeJsonStringify(a)} >= ${safeJsonStringify(b)} >= ${safeJsonStringify(c)}, but compare(a,c)=${ac}`);
				}
			}), { numRuns: 200 });
		});
	});

	// --- 8. Insert/Select Roundtrip ---
	describe('Insert/Select Roundtrip', () => {
		it('should roundtrip INTEGER values', async () => {
			await db.exec('CREATE TABLE rt_int (id INTEGER PRIMARY KEY, v INTEGER) USING memory');

			await fc.assert(fc.asyncProperty(fc.integer(), async (val) => {
				await db.exec('DELETE FROM rt_int');
				const stmt = db.prepare('INSERT INTO rt_int (id, v) VALUES (1, ?)');
				try { await stmt.run([val]); } finally { await stmt.finalize(); }

				for await (const row of db.eval('SELECT v FROM rt_int')) {
					expect(row.v).to.equal(val);
				}
			}), { numRuns: 100 });
		});

		it('should roundtrip REAL values', async () => {
			await db.exec('CREATE TABLE rt_real (id INTEGER PRIMARY KEY, v REAL) USING memory');

			await fc.assert(fc.asyncProperty(fc.float({ noNaN: true, noDefaultInfinity: true }), async (val) => {
				await db.exec('DELETE FROM rt_real');
				const stmt = db.prepare('INSERT INTO rt_real (id, v) VALUES (1, ?)');
				try { await stmt.run([val]); } finally { await stmt.finalize(); }

				for await (const row of db.eval('SELECT v FROM rt_real')) {
					// Account for -0 vs +0
					if (val === 0 && row.v === 0) return;
					expect(row.v).to.equal(val);
				}
			}), { numRuns: 100 });
		});

		it('should roundtrip TEXT values', async () => {
			await db.exec('CREATE TABLE rt_text (id INTEGER PRIMARY KEY, v TEXT) USING memory');

			await fc.assert(fc.asyncProperty(fc.string({ minLength: 0, maxLength: 100 }), async (val) => {
				await db.exec('DELETE FROM rt_text');
				const stmt = db.prepare('INSERT INTO rt_text (id, v) VALUES (1, ?)');
				try { await stmt.run([val]); } finally { await stmt.finalize(); }

				for await (const row of db.eval('SELECT v FROM rt_text')) {
					expect(row.v).to.equal(val);
				}
			}), { numRuns: 100 });
		});

		it('should roundtrip BLOB values', async () => {
			await db.exec('CREATE TABLE rt_blob (id INTEGER PRIMARY KEY, v BLOB) USING memory');

			await fc.assert(fc.asyncProperty(fc.uint8Array({ minLength: 0, maxLength: 100 }), async (val) => {
				await db.exec('DELETE FROM rt_blob');
				const stmt = db.prepare('INSERT INTO rt_blob (id, v) VALUES (1, ?)');
				try { await stmt.run([val]); } finally { await stmt.finalize(); }

				for await (const row of db.eval('SELECT v FROM rt_blob')) {
					expect(row.v).to.deep.equal(val);
				}
			}), { numRuns: 100 });
		});

		it('should roundtrip ANY column values exactly', async () => {
			await db.exec('CREATE TABLE rt_any (id INTEGER PRIMARY KEY, v ANY null) USING memory');

			const anyValueArb = fc.oneof(
				fc.constant(null),
				fc.integer(),
				fc.float({ noNaN: true, noDefaultInfinity: true }),
				fc.string({ minLength: 0, maxLength: 50 }),
				fc.boolean()
			);

			await fc.assert(fc.asyncProperty(anyValueArb, async (val) => {
				await db.exec('DELETE FROM rt_any');
				const stmt = db.prepare('INSERT INTO rt_any (id, v) VALUES (1, ?)');
				try { await stmt.run([val]); } finally { await stmt.finalize(); }

				for await (const row of db.eval('SELECT v FROM rt_any')) {
					if (val === null) {
						expect(row.v).to.be.null;
					} else if (typeof val === 'number' && val === 0) {
						// Account for -0 vs +0
						expect(row.v).to.equal(0);
					} else {
						expect(row.v).to.equal(val);
					}
				}
			}), { numRuns: 100 });
		});

		it('should roundtrip integer boundary values', async () => {
			await db.exec('CREATE TABLE rt_int_bounds (id INTEGER PRIMARY KEY, v INTEGER) USING memory');

			const boundaries = [
				Number.MAX_SAFE_INTEGER,   // 2^53-1
				Number.MIN_SAFE_INTEGER,   // -(2^53-1)
				0,
				-1,
				1,
				2 ** 31 - 1,               // INT32_MAX
				-(2 ** 31),                 // INT32_MIN
				2 ** 32 - 1,               // UINT32_MAX
			];

			for (const val of boundaries) {
				await db.exec('DELETE FROM rt_int_bounds');
				const stmt = db.prepare('INSERT INTO rt_int_bounds (id, v) VALUES (1, ?)');
				try { await stmt.run([val]); } finally { await stmt.finalize(); }

				for await (const row of db.eval('SELECT v FROM rt_int_bounds')) {
					expect(row.v).to.equal(val,
						`Integer boundary roundtrip failed for ${val}`);
				}
			}
		});

		it('should roundtrip bigint boundary values', async () => {
			await db.exec('CREATE TABLE rt_bigint_bounds (id INTEGER PRIMARY KEY, v INTEGER) USING memory');

			const boundaries: bigint[] = [
				BigInt('9223372036854775807'),   // 2^63-1 (INT64_MAX)
				BigInt('-9223372036854775808'),   // -2^63 (INT64_MIN)
				0n,
				1n,
				-1n,
				BigInt(Number.MAX_SAFE_INTEGER),
				BigInt(Number.MIN_SAFE_INTEGER),
			];

			for (const val of boundaries) {
				await db.exec('DELETE FROM rt_bigint_bounds');
				const stmt = db.prepare('INSERT INTO rt_bigint_bounds (id, v) VALUES (1, ?)');
				try { await stmt.run([val]); } finally { await stmt.finalize(); }

				for await (const row of db.eval('SELECT v FROM rt_bigint_bounds')) {
					// Values within safe integer range may come back as number
					if (val >= BigInt(Number.MIN_SAFE_INTEGER) && val <= BigInt(Number.MAX_SAFE_INTEGER)) {
						const actual = typeof row.v === 'bigint' ? row.v : BigInt(row.v as number);
						expect(actual).to.equal(val,
							`BigInt boundary roundtrip failed for ${val}: got ${row.v} (${typeof row.v})`);
					} else {
						expect(row.v).to.equal(val,
							`BigInt boundary roundtrip failed for ${val}`);
					}
				}
			}
		});

		it('should roundtrip special and edge-case strings', async () => {
			await db.exec('CREATE TABLE rt_str_edge (id INTEGER PRIMARY KEY, v TEXT) USING memory');

			const edgeStrings = [
				'',                                         // empty string
				'   ',                                      // whitespace only
				'\t\n\r',                                   // control whitespace
				'hello\0world',                             // embedded NUL
				'\0',                                       // just NUL
				'a'.repeat(10000),                          // 10K chars
				'123',                                      // numeric-looking
				'1.5e10',                                   // scientific notation string
				'NaN',                                      // NaN string
				'Infinity',                                 // Infinity string
				'-Infinity',                                // negative infinity string
				'0',                                        // zero string
				'-0',                                       // negative zero string
				'\u{1F600}',                                // emoji (😀)
				'\u{1F468}\u{200D}\u{1F469}\u{200D}\u{1F467}', // ZWJ family emoji
				'\u200F\u200E',                             // RTL/LTR marks
				'\u200B\u200C\u200D',                       // zero-width chars
				'مرحبا',                                    // Arabic (RTL)
				'SELECT * FROM t; DROP TABLE t; --',        // SQL injection attempt
				"it's a test",                              // single quote
				'say "hello"',                              // double quotes
			];

			for (const val of edgeStrings) {
				await db.exec('DELETE FROM rt_str_edge');
				const stmt = db.prepare('INSERT INTO rt_str_edge (id, v) VALUES (1, ?)');
				try { await stmt.run([val]); } finally { await stmt.finalize(); }

				for await (const row of db.eval('SELECT v FROM rt_str_edge')) {
					expect(row.v).to.equal(val,
						`String roundtrip failed for ${JSON.stringify(val)}`);
				}
			}
		});

		it('should roundtrip empty blob', async () => {
			await db.exec('CREATE TABLE rt_blob_empty (id INTEGER PRIMARY KEY, v BLOB) USING memory');

			const emptyBlob = new Uint8Array(0);
			const stmt = db.prepare('INSERT INTO rt_blob_empty (id, v) VALUES (1, ?)');
			try { await stmt.run([emptyBlob]); } finally { await stmt.finalize(); }

			for await (const row of db.eval('SELECT v FROM rt_blob_empty')) {
				expect(row.v).to.be.instanceOf(Uint8Array);
				expect((row.v as Uint8Array).length).to.equal(0,
					'Empty blob should roundtrip with length 0');
			}
		});

		it('should roundtrip NULL-heavy rows', async () => {
			await db.exec(`CREATE TABLE rt_nulls (
				id INTEGER PRIMARY KEY,
				int_col INTEGER null,
				real_col REAL null,
				text_col TEXT null,
				blob_col BLOB null,
				any_col ANY null
			) USING memory`);

			// Insert a row where every nullable column is NULL
			const stmt = db.prepare(
				'INSERT INTO rt_nulls (id, int_col, real_col, text_col, blob_col, any_col) VALUES (1, ?, ?, ?, ?, ?)'
			);
			try { await stmt.run([null, null, null, null, null]); } finally { await stmt.finalize(); }

			for await (const row of db.eval('SELECT int_col, real_col, text_col, blob_col, any_col FROM rt_nulls')) {
				expect(row.int_col).to.be.null;
				expect(row.real_col).to.be.null;
				expect(row.text_col).to.be.null;
				expect(row.blob_col).to.be.null;
				expect(row.any_col).to.be.null;
			}

			// Also test with multiple all-NULL rows
			await db.exec('DELETE FROM rt_nulls');
			for (let i = 1; i <= 10; i++) {
				const s = db.prepare(
					'INSERT INTO rt_nulls (id, int_col, real_col, text_col, blob_col, any_col) VALUES (?, ?, ?, ?, ?, ?)'
				);
				try { await s.run([i, null, null, null, null, null]); } finally { await s.finalize(); }
			}

			let rowCount = 0;
			for await (const row of db.eval('SELECT * FROM rt_nulls')) {
				rowCount++;
				expect(row.int_col).to.be.null;
				expect(row.real_col).to.be.null;
				expect(row.text_col).to.be.null;
				expect(row.blob_col).to.be.null;
				expect(row.any_col).to.be.null;
			}
			expect(rowCount).to.equal(10, 'Should have 10 all-NULL rows');
		});
	});

	// --- 9. Temporal Roundtrip ---
	describe('Temporal Roundtrip', () => {
		it('should roundtrip DATE values through date(text(date))', async () => {
			// Generate valid year/month/day combinations
			const dateArb = fc.tuple(
				fc.integer({ min: 1970, max: 2100 }),
				fc.integer({ min: 1, max: 12 }),
				fc.integer({ min: 1, max: 28 }) // Use 28 to avoid month-length issues
			).map(([y, m, d]) => `${y}-${String(m).padStart(2, '0')}-${String(d).padStart(2, '0')}`);

			await fc.assert(fc.asyncProperty(dateArb, async (dateStr) => {
				let result: any;
				for await (const row of db.eval(`select date('${dateStr}') as r`)) {
					result = row.r;
					break;
				}
				// date() should return the same normalized ISO date
				expect(result).to.equal(dateStr,
					`DATE roundtrip failed for ${dateStr}: got ${result}`);
			}), { numRuns: 100 });
		});

		it('should roundtrip TIME values through time(text)', async () => {
			const timeArb = fc.tuple(
				fc.integer({ min: 0, max: 23 }),
				fc.integer({ min: 0, max: 59 }),
				fc.integer({ min: 0, max: 59 })
			).map(([h, m, s]) =>
				`${String(h).padStart(2, '0')}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`
			);

			await fc.assert(fc.asyncProperty(timeArb, async (timeStr) => {
				let result: any;
				for await (const row of db.eval(`select time('${timeStr}') as r`)) {
					result = row.r;
					break;
				}
				expect(result).to.equal(timeStr,
					`TIME roundtrip failed for ${timeStr}: got ${result}`);
			}), { numRuns: 100 });
		});

		it('should roundtrip DATE boundary values', async () => {
			const boundaryDates = [
				'0001-01-01',    // earliest representable date
				'9999-12-31',    // latest representable date
				'2000-02-29',    // leap year (2000 is leap)
				'1900-02-28',    // non-leap year (1900 is not leap despite /100)
				'2024-02-29',    // recent leap year
				'1970-01-01',    // Unix epoch
			];

			for (const dateStr of boundaryDates) {
				let result: any;
				for await (const row of db.eval(`select date('${dateStr}') as r`)) {
					result = row.r;
					break;
				}
				expect(result).to.equal(dateStr,
					`DATE boundary roundtrip failed for ${dateStr}: got ${result}`);
			}
		});

		it('should roundtrip TIME boundary values', async () => {
			const boundaryTimes: Array<[string, string]> = [
				['00:00:00', '00:00:00'],             // midnight
				['23:59:59', '23:59:59'],             // last second of day
				['12:00:00', '12:00:00'],             // noon
				['12:00:00.000', '12:00:00'],         // fractional zeros normalize
				['23:59:59.999', '23:59:59.999'],     // last millisecond
			];

			for (const [timeStr, expected] of boundaryTimes) {
				let result: any;
				for await (const row of db.eval(`select time('${timeStr}') as r`)) {
					result = row.r;
					break;
				}
				expect(result).to.equal(expected,
					`TIME boundary roundtrip failed for ${timeStr}: got ${result}`);
			}
		});

		it('should roundtrip DATETIME boundary values', async () => {
			const boundaryDatetimes: Array<[string, string]> = [
				['0001-01-01 00:00:00', '0001-01-01T00:00:00'],
				['9999-12-31 23:59:59', '9999-12-31T23:59:59'],
				['1970-01-01 00:00:00', '1970-01-01T00:00:00'],
				['2000-02-29 12:30:45', '2000-02-29T12:30:45'],
			];

			for (const [dtStr, expected] of boundaryDatetimes) {
				let result: any;
				for await (const row of db.eval(`select datetime('${dtStr}') as r`)) {
					result = row.r;
					break;
				}
				expect(result).to.equal(expected,
					`DATETIME boundary roundtrip failed for ${dtStr}: got ${result}`);
			}
		});
	});

	// --- 10. Conversion Idempotency ---
	describe('Conversion Idempotency', () => {
		it('integer(integer(x)) = integer(x) for valid integers', async () => {
			await fc.assert(fc.asyncProperty(fc.integer({ min: -1000000, max: 1000000 }), async (val) => {
				let single: any;
				for await (const row of db.eval(`select integer(${val}) as r`)) {
					single = row.r;
					break;
				}
				let double: any;
				for await (const row of db.eval(`select integer(integer(${val})) as r`)) {
					double = row.r;
					break;
				}
				expect(double).to.equal(single,
					`Idempotency violated: integer(integer(${val})) = ${double}, integer(${val}) = ${single}`);
			}), { numRuns: 100 });
		});

		it('real(real(x)) = real(x) for valid reals', async () => {
			await fc.assert(fc.asyncProperty(
				fc.float({ min: -1000, max: 1000, noNaN: true, noDefaultInfinity: true }),
				async (val) => {
					let single: any;
					for await (const row of db.eval(`select real(${val}) as r`)) {
						single = row.r;
						break;
					}
					let double: any;
					for await (const row of db.eval(`select real(real(${val})) as r`)) {
						double = row.r;
						break;
					}
					if (single === null) {
						expect(double).to.be.null;
					} else if (typeof single === 'number' && single === 0) {
						expect(double).to.equal(0);
					} else {
						expect(double).to.equal(single,
							`Idempotency violated: real(real(${val})) = ${double}, real(${val}) = ${single}`);
					}
				}
			), { numRuns: 100 });
		});

		it('text(text(x)) = text(x) for strings', async () => {
			await fc.assert(fc.asyncProperty(
				fc.string({ minLength: 0, maxLength: 50 }),
				async (val) => {
					// Use parameterized query to avoid SQL injection issues with special chars
					let single: any;
					for await (const row of db.eval('select text(?) as r', [val])) {
						single = row.r;
						break;
					}
					let double: any;
					for await (const row of db.eval('select text(text(?)) as r', [val])) {
						double = row.r;
						break;
					}
					expect(double).to.equal(single,
						`Idempotency violated for text('${val}')`);
				}
			), { numRuns: 100 });
		});
	});

	// --- 11. Transaction Isolation ---
	describe('Transaction Isolation', () => {
		it('should never see partial transaction state via read after commit', async () => {
			await db.exec('CREATE TABLE iso_t (id INTEGER PRIMARY KEY, val INTEGER) USING memory');

			// Seed initial rows
			for (let i = 1; i <= 5; i++) {
				await db.exec(`INSERT INTO iso_t VALUES (${i}, ${i * 10})`);
			}

			await fc.assert(fc.asyncProperty(
				// Generate a random set of mutations per transaction
				fc.array(fc.tuple(
					fc.constantFrom('insert', 'update', 'delete'),
					fc.integer({ min: 1, max: 20 }),
					fc.integer({ min: 0, max: 100 }),
				), { minLength: 1, maxLength: 5 }),
				async (mutations) => {
					// Start explicit transaction
					await db.exec('BEGIN');

					try {
						for (const [op, id, val] of mutations) {
							try {
								if (op === 'insert') {
									await db.exec(`INSERT OR IGNORE INTO iso_t VALUES (${id}, ${val})`);
								} else if (op === 'update') {
									await db.exec(`UPDATE iso_t SET val = ${val} WHERE id = ${id}`);
								} else {
									await db.exec(`DELETE FROM iso_t WHERE id = ${id}`);
								}
							} catch {
								// Constraint violations are expected — continue
							}
						}
					} finally {
						await db.exec('ROLLBACK');
					}

					// After rollback, all rows should match their original values
					const rows: Array<{ id: number; val: number }> = [];
					for await (const row of db.eval('SELECT id, val FROM iso_t ORDER BY id')) {
						rows.push(row as { id: number; val: number });
					}

					// Exactly the original 5 rows with original values
					expect(rows).to.have.length(5);
					for (const row of rows) {
						expect(row.val).to.equal(row.id * 10,
							`Row ${row.id} has wrong value after rollback: expected ${row.id * 10}, got ${row.val}`);
					}
				}
			), { numRuns: 50 });
		});

		it('should preserve schema DDL through rollback', async () => {
			await fc.assert(fc.asyncProperty(
				fc.integer({ min: 1, max: 100 }),
				async (tableId) => {
					const tableName = `ddl_test_${tableId}`;

					// Ensure clean state
					await db.exec(`DROP TABLE IF EXISTS ${tableName}`);

					// Create in committed context
					await db.exec(`CREATE TABLE ${tableName} (id INTEGER PRIMARY KEY, val TEXT)`);

					// Start transaction, insert data, rollback
					await db.exec('BEGIN');
					try {
						await db.exec(`INSERT INTO ${tableName} VALUES (1, 'test')`);
					} finally {
						await db.exec('ROLLBACK');
					}

					// Table should still exist but be empty
					const rows: unknown[] = [];
					for await (const row of db.eval(`SELECT * FROM ${tableName}`)) {
						rows.push(row);
					}
					expect(rows).to.have.length(0);

					// Cleanup
					await db.exec(`DROP TABLE ${tableName}`);
				}
			), { numRuns: 20 });
		});
	});

	// --- 12. ORDER BY Stability ---
	describe('ORDER BY Stability', () => {
		it('should produce identical results for repeated ORDER BY on same data', async () => {
			await db.exec('CREATE TABLE stab_t (id INTEGER PRIMARY KEY, sort_key INTEGER, payload TEXT) USING memory');

			await fc.assert(fc.asyncProperty(
				fc.array(fc.tuple(fc.integer({ min: 1, max: 5 }), fc.string({ minLength: 1, maxLength: 10 })), { minLength: 2, maxLength: 20 }),
				async (rows) => {
					await db.exec('DELETE FROM stab_t');
					const stmt = db.prepare('INSERT INTO stab_t (id, sort_key, payload) VALUES (?, ?, ?)');
					try {
						for (let i = 0; i < rows.length; i++) {
							await stmt.run([i + 1, rows[i][0], rows[i][1]]);
						}
					} finally {
						await stmt.finalize();
					}

					// Run ORDER BY twice
					const run1: any[] = [];
					for await (const row of db.eval('SELECT id, sort_key, payload FROM stab_t ORDER BY sort_key, id')) {
						run1.push(row);
					}

					const run2: any[] = [];
					for await (const row of db.eval('SELECT id, sort_key, payload FROM stab_t ORDER BY sort_key, id')) {
						run2.push(row);
					}

					expect(run1).to.deep.equal(run2, 'ORDER BY should produce identical results across repeated executions');
				}
			), { numRuns: 100 });
		});
	});

	// --- 13. Window Function Invariants ---
	describe('Window Function Invariants', () => {
		it('row_number() produces contiguous 1..N (unpartitioned)', async () => {
			await db.exec('CREATE TABLE wf_rn (id INTEGER PRIMARY KEY, val INTEGER) USING memory');

			await fc.assert(fc.asyncProperty(
				fc.array(fc.integer({ min: -1000, max: 1000 }), { minLength: 1, maxLength: 50 }),
				async (values) => {
					await db.exec('DELETE FROM wf_rn');
					const stmt = db.prepare('INSERT INTO wf_rn (id, val) VALUES (?, ?)');
					try {
						for (let i = 0; i < values.length; i++) {
							await stmt.run([i + 1, values[i]]);
						}
					} finally {
						await stmt.finalize();
					}

					const rowNums: number[] = [];
					for await (const row of db.eval('select row_number() over (order by id) as rn from wf_rn')) {
						rowNums.push(row.rn as number);
					}

					expect(rowNums.length).to.equal(values.length);
					const expected = Array.from({ length: values.length }, (_, i) => i + 1);
					expect(rowNums).to.deep.equal(expected,
						`row_number() should produce contiguous 1..${values.length}, got ${JSON.stringify(rowNums)}`);
				}
			), { numRuns: 50 });
		});

		it('partitioned row_number() produces 1..K per partition', async () => {
			await db.exec('CREATE TABLE wf_prn (id INTEGER PRIMARY KEY, grp INTEGER NOT NULL, val INTEGER) USING memory');

			await fc.assert(fc.asyncProperty(
				fc.array(
					fc.record({
						grp: fc.integer({ min: 1, max: 3 }),
						val: fc.integer({ min: -1000, max: 1000 }),
					}),
					{ minLength: 1, maxLength: 50 }
				),
				async (rows) => {
					await db.exec('DELETE FROM wf_prn');
					const stmt = db.prepare('INSERT INTO wf_prn (id, grp, val) VALUES (?, ?, ?)');
					try {
						for (let i = 0; i < rows.length; i++) {
							await stmt.run([i + 1, rows[i].grp, rows[i].val]);
						}
					} finally {
						await stmt.finalize();
					}

					const results: Array<{ grp: number; rn: number }> = [];
					for await (const row of db.eval(
						'select grp, row_number() over (partition by grp order by id) as rn from wf_prn'
					)) {
						results.push({ grp: row.grp as number, rn: row.rn as number });
					}

					// Group results by partition
					const partitions = new Map<number, number[]>();
					for (const r of results) {
						const arr = partitions.get(r.grp) ?? [];
						arr.push(r.rn);
						partitions.set(r.grp, arr);
					}

					// Each partition should have contiguous 1..K
					for (const [grp, rns] of partitions) {
						const expected = Array.from({ length: rns.length }, (_, i) => i + 1);
						expect(rns).to.deep.equal(expected,
							`Partition ${grp}: row_number() should be 1..${rns.length}, got ${JSON.stringify(rns)}`);
					}
				}
			), { numRuns: 50 });
		});

		it('running sum via window equals cumulative sum', async () => {
			await db.exec('CREATE TABLE wf_rsum (id INTEGER PRIMARY KEY, val INTEGER NOT NULL) USING memory');

			await fc.assert(fc.asyncProperty(
				fc.array(fc.integer({ min: -100, max: 100 }), { minLength: 1, maxLength: 50 }),
				async (values) => {
					await db.exec('DELETE FROM wf_rsum');
					const stmt = db.prepare('INSERT INTO wf_rsum (id, val) VALUES (?, ?)');
					try {
						for (let i = 0; i < values.length; i++) {
							await stmt.run([i + 1, values[i]]);
						}
					} finally {
						await stmt.finalize();
					}

					const windowSums: number[] = [];
					for await (const row of db.eval(
						'select val, sum(val) over (order by id rows between unbounded preceding and current row) as running from wf_rsum order by id'
					)) {
						windowSums.push(row.running as number);
					}

					// Compute expected cumulative sums independently
					const expectedSums: number[] = [];
					let cumSum = 0;
					for (const v of values) {
						cumSum += v;
						expectedSums.push(cumSum);
					}

					expect(windowSums).to.deep.equal(expectedSums,
						`Running sum mismatch: window=${JSON.stringify(windowSums)}, expected=${JSON.stringify(expectedSums)}`);
				}
			), { numRuns: 50 });
		});

		it('total window sum equals aggregate sum', async () => {
			await db.exec('CREATE TABLE wf_tsum (id INTEGER PRIMARY KEY, val INTEGER NOT NULL) USING memory');

			await fc.assert(fc.asyncProperty(
				fc.array(fc.integer({ min: -100, max: 100 }), { minLength: 1, maxLength: 50 }),
				async (values) => {
					await db.exec('DELETE FROM wf_tsum');
					const stmt = db.prepare('INSERT INTO wf_tsum (id, val) VALUES (?, ?)');
					try {
						for (let i = 0; i < values.length; i++) {
							await stmt.run([i + 1, values[i]]);
						}
					} finally {
						await stmt.finalize();
					}

					// Get aggregate sum
					let aggSum: number | null = null;
					for await (const row of db.eval('select sum(val) as s from wf_tsum')) {
						aggSum = row.s as number;
					}

					// Get window sum on every row (unpartitioned, no order = full frame)
					const windowSums: number[] = [];
					for await (const row of db.eval('select sum(val) over () as wsum from wf_tsum')) {
						windowSums.push(row.wsum as number);
					}

					expect(windowSums.length).to.equal(values.length);
					for (let i = 0; i < windowSums.length; i++) {
						expect(windowSums[i]).to.equal(aggSum,
							`Row ${i}: window sum(val) over () = ${windowSums[i]}, but aggregate sum = ${aggSum}`);
					}
				}
			), { numRuns: 50 });
		});

		it('rank() and dense_rank() tie consistency', async () => {
			await db.exec('CREATE TABLE wf_rank (id INTEGER PRIMARY KEY, sort_key INTEGER NOT NULL) USING memory');

			await fc.assert(fc.asyncProperty(
				fc.array(fc.integer({ min: 1, max: 10 }), { minLength: 2, maxLength: 50 }),
				async (keys) => {
					await db.exec('DELETE FROM wf_rank');
					const stmt = db.prepare('INSERT INTO wf_rank (id, sort_key) VALUES (?, ?)');
					try {
						for (let i = 0; i < keys.length; i++) {
							await stmt.run([i + 1, keys[i]]);
						}
					} finally {
						await stmt.finalize();
					}

					const results: Array<{ sort_key: number; rnk: number; drnk: number }> = [];
					for await (const row of db.eval(
						'select sort_key, rank() over (order by sort_key) as rnk, dense_rank() over (order by sort_key) as drnk from wf_rank'
					)) {
						results.push({
							sort_key: row.sort_key as number,
							rnk: row.rnk as number,
							drnk: row.drnk as number,
						});
					}

					// Verify: rows with the same sort_key must have the same rank and dense_rank
					const rankByKey = new Map<number, number>();
					const denseRankByKey = new Map<number, number>();
					for (const r of results) {
						if (rankByKey.has(r.sort_key)) {
							expect(r.rnk).to.equal(rankByKey.get(r.sort_key),
								`rank() inconsistent for sort_key=${r.sort_key}`);
						} else {
							rankByKey.set(r.sort_key, r.rnk);
						}
						if (denseRankByKey.has(r.sort_key)) {
							expect(r.drnk).to.equal(denseRankByKey.get(r.sort_key),
								`dense_rank() inconsistent for sort_key=${r.sort_key}`);
						} else {
							denseRankByKey.set(r.sort_key, r.drnk);
						}
					}

					// Verify: dense_rank values have no gaps (should be 1, 2, 3, ...)
					const distinctDenseRanks = [...new Set(results.map(r => r.drnk))].sort((a, b) => a - b);
					const expectedDenseRanks = Array.from({ length: distinctDenseRanks.length }, (_, i) => i + 1);
					expect(distinctDenseRanks).to.deep.equal(expectedDenseRanks,
						`dense_rank() should have no gaps: got ${JSON.stringify(distinctDenseRanks)}`);

					// Verify: rank() of first occurrence matches position
					// rank(x) = 1 + count of rows with sort_key < x
					const sortedKeys = [...keys].sort((a, b) => a - b);
					for (const [key, rnk] of rankByKey) {
						const expectedRank = sortedKeys.indexOf(key) + 1;
						expect(rnk).to.equal(expectedRank,
							`rank() for sort_key=${key}: expected ${expectedRank}, got ${rnk}`);
					}
				}
			), { numRuns: 50 });
		});
	});

	// --- 14. Declarative-schema equivalence ---
	// Generates a small constrained table shape, builds two DBs in parallel
	// (canonical `create table` vs `declare schema {...} apply schema`), and
	// asserts the two end up indistinguishable at the catalog level AND under
	// the same DML probes. Acts as the dragnet behind the curated
	// `declarative-equivalence.spec.ts` corpus.
	//
	// Gated to `numRuns: 50` by default; set `PROPERTY_LONG=1` for `numRuns: 200`.
	describe('Declarative-schema equivalence (property)', () => {
		const NUM_RUNS = process.env.PROPERTY_LONG ? 200 : 50;

		const identArb = fc.stringMatching(/^[a-z][a-z0-9_]{2,7}$/).filter(s => !RESERVED.has(s));
		const colTypeArb = fc.constantFrom('integer', 'text');
		const literalArb: fc.Arbitrary<{ sql: string; jsValue: unknown }> = fc.oneof(
			fc.integer({ min: 0, max: 1000 }).map(n => ({ sql: String(n), jsValue: n })),
			fc.stringMatching(/^[a-z0-9 ]{1,8}$/).map(s => ({ sql: `'${s}'`, jsValue: s })),
		);

		/** A simple CHECK predicate against a single column. */
		function checkExprArb(colName: string, type: 'integer' | 'text'): fc.Arbitrary<string> {
			if (type === 'integer') {
				return fc.oneof(
					fc.integer({ min: 0, max: 100 }).map(n => `${colName} >= ${n}`),
					fc.integer({ min: 1, max: 100 }).map(n => `${colName} < ${n}`),
				);
			}
			return fc.oneof(
				fc.constant(`${colName} is not null`),
				fc.stringMatching(/^[a-z]{1,4}$/).map(s => `${colName} <> '${s}'`),
			);
		}

		interface ColumnShape {
			name: string;
			type: 'integer' | 'text';
			notNull: boolean;
			default?: { sql: string; jsValue: unknown };
		}

		interface TableShape {
			tableName: string;
			columns: ColumnShape[];
			pkColumn: string;
			checks: Array<{ name: string; sql: string }>;
		}

		function tableShapeArb(): fc.Arbitrary<TableShape> {
			return fc.tuple(
				identArb,
				fc.uniqueArray(identArb, { minLength: 2, maxLength: 3 }),
			).chain(([tableName, colNames]) => {
				const colShapeArbs = colNames.map((name, i) => {
					// First column is always integer PK to keep the shape valid for FK
					// experiments and to give probes a deterministic id to insert.
					if (i === 0) {
						return fc.constant<ColumnShape>({ name, type: 'integer', notNull: true });
					}
					return fc.record({
						type: colTypeArb,
						notNull: fc.boolean(),
						defaultOpt: fc.option(literalArb, { nil: undefined }),
					}).map(({ type, notNull, defaultOpt }): ColumnShape => ({
						name,
						type,
						notNull,
						default: defaultOpt,
					}));
				});
				return fc.tuple(...colShapeArbs).chain(columns => {
					const cols = columns as ColumnShape[];
					// Pick at most 1 CHECK over a single non-PK column to keep arbitrary inside the parser's accepted region.
					const checkableCol = cols.find(c => c.name !== cols[0].name);
					const checksArb: fc.Arbitrary<Array<{ name: string; sql: string }>> =
						checkableCol
							? fc.option(
								checkExprArb(checkableCol.name, checkableCol.type).map((sql, idx) => [{ name: `chk_${idx}`, sql }]),
								{ nil: [] as Array<{ name: string; sql: string }> },
							)
							: fc.constant([] as Array<{ name: string; sql: string }>);
					return checksArb.map(checks => ({
						tableName,
						columns: cols,
						pkColumn: cols[0].name,
						checks,
					}));
				});
			});
		}

		function renderCanonicalDDL(shape: TableShape): string {
			const colSqls = shape.columns.map(c => {
				const parts = [c.name, c.type.toUpperCase()];
				if (c.name === shape.pkColumn) parts.push('primary key');
				if (c.notNull && c.name !== shape.pkColumn) parts.push('not null');
				if (c.default) parts.push(`default ${c.default.sql}`);
				return parts.join(' ');
			});
			const checkSqls = shape.checks.map(c => `constraint ${c.name} check (${c.sql})`);
			return `create table ${shape.tableName} (${[...colSqls, ...checkSqls].join(', ')})`;
		}

		function renderDeclarativeBody(shape: TableShape): string {
			const colLines = shape.columns.map(c => {
				const parts = [c.name, c.type.toUpperCase()];
				if (c.name === shape.pkColumn) parts.push('PRIMARY KEY');
				if (c.notNull && c.name !== shape.pkColumn) parts.push('NOT NULL');
				if (c.default) parts.push(`DEFAULT ${c.default.sql}`);
				return '\t' + parts.join(' ');
			});
			const checkLines = shape.checks.map(c => `\tconstraint ${c.name} check (${c.sql})`);
			return `table ${shape.tableName} {\n${[...colLines, ...checkLines].join(',\n')}\n}`;
		}

		it('canonical DDL ≡ declarative body at the catalog + probe level', async function () {
			await fc.assert(fc.asyncProperty(tableShapeArb(), async (shape) => {
				const canonicalDDL = renderCanonicalDDL(shape);
				const declarativeBody = renderDeclarativeBody(shape);

				const directDb = new Database();
				const appliedDb = new Database();
				try {
					await directDb.exec(canonicalDDL);
					await appliedDb.exec(`declare schema main {\n${declarativeBody}\n}`);
					await appliedDb.exec('apply schema main');

					const directTbl = directDb.schemaManager.getTable('main', shape.tableName);
					const appliedTbl = appliedDb.schemaManager.getTable('main', shape.tableName);
					if (!directTbl || !appliedTbl) {
						throw new Error(`table missing  canonicalDDL: ${canonicalDDL}\n  declarativeBody: ${declarativeBody}`);
					}
					try {
						assertTableSchemaEqual(directTbl, appliedTbl, shape.tableName);
					} catch (e) {
						const msg = e instanceof Error ? e.message : String(e);
						throw new Error(`${msg}\n  canonicalDDL:    ${canonicalDDL}\n  declarativeBody: ${declarativeBody}`);
					}

					// One simple count probe (cheap; catalog compare is the strong oracle here).
					await assertProbeEquivalent(directDb, appliedDb, {
						sql: `select count(*) as n from ${shape.tableName}`,
						expect: { rows: [{ n: 0 }] },
					}, shape.tableName);
				} finally {
					await directDb.close();
					await appliedDb.close();
				}
			}), { numRuns: NUM_RUNS });
		});
	});

	// --- 15. Key soundness ---
	// The empirical backstop for the unified uniqueness surface: for a spread of
	// query shapes (the node zoo) over randomly-seeded small tables, read the
	// claimed keys (`keysOf`) and set-ness (`isSet`) off the top relational
	// result node and assert the *materialized* rows never contradict them. A
	// claimed key must be all-distinct; `isSet` must mean the full rows are
	// distinct. An over-claim (a key that does not actually hold) reds the test.
	//
	// Soundness, not completeness: a *missing* key is fine; a *false* key is not.
	//
	// Tier 1 asserts at the top result node for every shape. Tier 2 walks every
	// relational node in the *optimized* plan tree, materializes each node in
	// isolation (emit + Scheduler.run), and runs the same assertions on that
	// node's own rows — pinning the soundness of each operator's getType() /
	// computePhysical independent of whether a shape surfaces it at the top.
	// Tier 2 is best-effort: correlated / parameterized inner nodes cannot emit
	// standalone, so emission/run failures *skip* rather than fail the test.
	describe('Key Soundness', () => {
		/** Stable, type-aware signature for a tuple of SqlValues. */
		function tupleSig(values: SqlValue[]): string {
			return values.map(v => {
				if (v === null || v === undefined) return 'N';
				if (v instanceof Uint8Array) return 'B:' + Array.from(v).join('.');
				return typeof v + ':' + String(v);
			}).join('|');
		}

		/**
		 * Positional core of the soundness check: throws on the first
		 * contradiction between the claimed uniqueness facts and the actual rows,
		 * where each row is a tuple of values ordered to match the node's columns
		 * and each key is a list of column indices. Shared by Tier 1 (result node,
		 * via the record adapter below) and Tier 2 (isolated per-node rows).
		 */
		function checkKeysAndSet(
			label: string,
			keys: readonly (readonly number[])[],
			isSet: boolean,
			rows: readonly SqlValue[][],
		): void {
			for (const key of keys) {
				if (key.length === 0) {
					// The empty key claims at-most-one-row.
					if (rows.length > 1) {
						throw new Error(`over-claim: empty key claims ≤1 row but ${label} returned ${rows.length}`);
					}
					continue;
				}
				const seen = new Set<string>();
				for (const row of rows) {
					const sig = tupleSig(key.map(i => row[i]));
					if (seen.has(sig)) {
						throw new Error(`over-claim: key [${key}] is not unique on ${label} (duplicate ${sig})`);
					}
					seen.add(sig);
				}
			}
			if (isSet) {
				const seen = new Set<string>();
				for (const row of rows) {
					const sig = tupleSig(row);
					if (seen.has(sig)) {
						throw new Error(`over-claim: isSet=true but full rows are not distinct on ${label}`);
					}
					seen.add(sig);
				}
			}
		}

		/**
		 * Record adapter over {@link checkKeysAndSet}: projects each row-object to
		 * a positional tuple in `cols` order. Shared by the Tier-1 property below
		 * and the negative self-test that proves the check fails loudly.
		 */
		function checkNoOverClaim(
			q: string,
			keys: readonly (readonly number[])[],
			isSet: boolean,
			cols: readonly string[],
			rows: readonly Record<string, SqlValue>[],
		): void {
			const positional = rows.map(row => cols.map(c => row[c]));
			checkKeysAndSet(`\`${q}\``, keys, isSet, positional);
		}

		// Query shapes spanning the node zoo, shared by both tiers. Output column
		// names are kept distinct so the row-object lookup by name is unambiguous.
		const queries = [
			'select a, b, c from ta',                                            // bare scan (set on [a])
			'select b, c from ta',                                               // projection drops the key (bag)
			'select b from ta',                                                  // single-column key-dropping projection
			'select distinct b, c from ta',                                      // DISTINCT (set on all cols)
			'select distinct b from ta',
			'select b, count(*) as n from ta group by b',                        // GROUP BY (key on group col)
			'select a, b, c from ta group by a, b, c',                           // all-columns GROUP BY
			'select b, c from ta group by b, c',
			'select a, b, c from ta order by b',                                 // ORDER BY
			'select a, b, c from ta order by b limit 3',                         // LIMIT
			'select a, b, c from ta union all select d, e, e from tb',           // UNION ALL (bag)
			'select a, b, c from ta union select d, e, e from tb',               // UNION (set)
			'select b, c from ta intersect select e, e from tb',                 // INTERSECT (set)
			'select b, c from ta except select e, e from tb',                    // EXCEPT (set)
			'select ta.a as ja, tb.d as jd, ta.b as jb from ta join tb on ta.b = tb.d', // inner join
			'select ta.a as la, tb.d as ld from ta left join tb on ta.b = tb.d', // left join
			'select ta.a as xa, tb.d as xd, ta.c as xc from ta cross join tb',   // cross join
			'select x, y from (select distinct b as x, c as y from ta)',         // projection over inner DISTINCT
			'select distinct x, y from (select distinct b as x, c as y from ta)',// nested DISTINCT
		];

		const rowArbA = fc.record({
			a: fc.integer({ min: 1, max: 8 }),
			b: fc.integer({ min: 1, max: 3 }),
			c: fc.integer({ min: 1, max: 3 }),
		});
		const rowArbB = fc.record({
			d: fc.integer({ min: 1, max: 8 }),
			e: fc.integer({ min: 1, max: 3 }),
		});

		/** Create the two source tables (fresh `db` per `beforeEach`). */
		async function createTables(): Promise<void> {
			await db.exec('create table ta (a integer primary key, b integer, c integer) using memory');
			await db.exec('create table tb (d integer primary key, e integer) using memory');
		}

		/** Replace table contents with the generated rows, deduped by PK. */
		async function seedTables(rowsA: { a: number; b: number; c: number }[], rowsB: { d: number; e: number }[]): Promise<void> {
			await db.exec('delete from ta');
			await db.exec('delete from tb');
			const seenA = new Set<number>();
			for (const r of rowsA) {
				if (seenA.has(r.a)) continue;
				seenA.add(r.a);
				await db.exec(`insert into ta values (${r.a}, ${r.b}, ${r.c})`);
			}
			const seenB = new Set<number>();
			for (const r of rowsB) {
				if (seenB.has(r.d)) continue;
				seenB.add(r.d);
				await db.exec(`insert into tb values (${r.d}, ${r.e})`);
			}
		}

		/** Collect every relational node in a plan tree, deduped by node id. */
		function collectRelationalNodes(rootNode: PlanNode): RelationalPlanNode[] {
			const out: RelationalPlanNode[] = [];
			const seen = new Set<string>();
			const stack: PlanNode[] = [rootNode];
			while (stack.length > 0) {
				const n = stack.pop()!;
				if (seen.has(n.id)) continue;
				seen.add(n.id);
				if (isRelationalNode(n)) out.push(n);
				for (const child of n.getChildren()) stack.push(child);
			}
			return out;
		}

		/**
		 * Emit + run a single relational node in isolation and collect its rows as
		 * positional tuples (column order matches `node.getType().columns`). Mirrors
		 * `scheduler_program` (func/builtins/explain.ts) and the runtime-context
		 * construction in `Database._executeSingleStatement`. Throws if the node
		 * cannot emit/run standalone (e.g. correlated / parameterized) — Tier 2
		 * treats that as a skip.
		 */
		async function materializeNode(node: RelationalPlanNode): Promise<SqlValue[][]> {
			const emissionContext = new EmissionContext(db);
			const rootInstruction = emitPlanNode(node, emissionContext);
			const scheduler = new Scheduler(rootInstruction);
			const runtimeCtx: RuntimeContext = {
				db,
				stmt: undefined,
				params: {},
				context: createStrictRowContextMap(),
				tableContexts: wrapTableContextsStrict(new Map()),
				tracer: undefined,
				enableMetrics: false,
			};
			const output = scheduler.run(runtimeCtx);
			const resolved = output instanceof Promise ? await output : output;
			if (!isAsyncIterable(resolved)) {
				throw new Error('node did not produce a row stream');
			}
			const rows: SqlValue[][] = [];
			for await (const row of resolved as AsyncIterable<Row>) {
				rows.push(row as SqlValue[]);
			}
			return rows;
		}

		it('the soundness check fails loudly on an injected over-claim', () => {
			const cols = ['x', 'y'];
			// `x` repeats across rows, so claiming [0] (x) is a key is an over-claim.
			const rows = [{ x: 1 as SqlValue, y: 1 as SqlValue }, { x: 1 as SqlValue, y: 2 as SqlValue }];
			expect(() => checkNoOverClaim('injected', [[0]], false, cols, rows)).to.throw(/over-claim/);
			// Duplicate full rows contradict an injected isSet=true.
			const dupRows = [{ x: 1 as SqlValue, y: 1 as SqlValue }, { x: 1 as SqlValue, y: 1 as SqlValue }];
			expect(() => checkNoOverClaim('injected', [], true, cols, dupRows)).to.throw(/over-claim/);
			// The honest case does not throw.
			expect(() => checkNoOverClaim('honest', [[0]], false, cols, [{ x: 1, y: 1 }, { x: 2, y: 9 }])).to.not.throw();
		});

		it('keysOf / isSet never over-claim on materialized result rows', async () => {
			await createTables();

			await fc.assert(fc.asyncProperty(
				fc.array(rowArbA, { minLength: 0, maxLength: 12 }),
				fc.array(rowArbB, { minLength: 0, maxLength: 12 }),
				fc.constantFrom(...queries),
				async (rowsA, rowsB, q) => {
					await seedTables(rowsA, rowsB);

					const block = db.getPlan(q) as any;
					const root = block.getRelations?.()[0];
					if (!root) return;
					const cols: string[] = root.getType().columns.map((c: any) => c.name);
					const keys = keysOf(root);
					const isSet: boolean = root.getType().isSet;

					const rows: Record<string, SqlValue>[] = [];
					for await (const row of db.eval(q)) rows.push(row as Record<string, SqlValue>);

					checkNoOverClaim(q, keys, isSet, cols, rows);
				},
			), { numRuns: 50 });
		});

		// Tier 2: walk every relational node in the optimized tree and assert the
		// invariants on each node's own materialized rows. Best-effort — nodes that
		// cannot emit/run standalone (correlated / parameterized inner nodes) are
		// skipped. A skip never fails the test; only an actual over-claim does.
		it('keysOf / isSet never over-claim on any isolated inner node (Tier 2)', async () => {
			await createTables();

			let checkedNodes = 0;
			let skippedNodes = 0;

			await fc.assert(fc.asyncProperty(
				fc.array(rowArbA, { minLength: 0, maxLength: 12 }),
				fc.array(rowArbB, { minLength: 0, maxLength: 12 }),
				fc.constantFrom(...queries),
				async (rowsA, rowsB, q) => {
					await seedTables(rowsA, rowsB);

					const block = db.getPlan(q) as unknown as PlanNode;
					const nodes = collectRelationalNodes(block);

					for (const node of nodes) {
						const type = node.getType();
						const keys = keysOf(node);
						const isSet = type.isSet;
						// Nothing claimed ⇒ nothing to contradict; skip the isolated run.
						if (keys.length === 0 && !isSet) continue;

						let rows: SqlValue[][];
						try {
							rows = await materializeNode(node);
						} catch {
							// Correlated / parameterized inner nodes won't emit/run
							// standalone — this tier is a bonus, not a gate.
							skippedNodes++;
							continue;
						}

						checkedNodes++;
						checkKeysAndSet(`${node.nodeType}[${node.id}] of \`${q}\``, keys, isSet, rows);
					}
				},
			), { numRuns: 50 });

			// Sanity: across the shape zoo at least some inner nodes must have
			// materialized, or the tier is silently a no-op.
			expect(checkedNodes, `Tier 2 checked no inner nodes (skipped ${skippedNodes})`).to.be.greaterThan(0);
		});
	});

	// --- 16. View Round-Trip Laws ---
	// The backward-direction dual of Key Soundness. Key Soundness keeps the
	// FORWARD relational walk honest (claimed keys / isSet never over-claim on
	// materialized rows). This block keeps the BACKWARD walk that drives view
	// write-through (`analysis/update-lineage.ts` → the Phase-1 rewrite in
	// `building/view-mutation.ts`) in lock-step with those forward FD facts, over
	// the single-source projection-and-filter shape the backward walk admits today.
	//
	// Three laws, per docs/view-updateability.md § "Round-Trip Laws and the
	// Derived Backward Walk":
	//   - PutGet  — a mutation through the view never escapes the view predicate;
	//               computed columns are read-only (rejected, not silently dropped).
	//   - GetPut  — reading a row and writing the same values back is a no-op on
	//               the base table.
	//   - Lineage — the backward lineage (`deriveViewColumns`) agrees with the
	//               forward FD facts (`keysOf` / `isUnique`): forward keys are
	//               base-writable and reconstruct the base identifying predicate.
	//
	// Structured exactly like Key Soundness: pure law cores plus a negative
	// self-test that proves each core reds on an injected violation.
	describe('View Round-Trip Laws', () => {
		type BaseRow = { id: number; a: number; b: number };

		/** One output column of a planned view body, by backward lineage. */
		interface ModelCol {
			readonly name: string;
			/** lowercased base column name, or undefined when the column is computed. */
			readonly base?: string;
		}

		// The view-body zoo: the single-source projection-and-filter shapes the
		// `93.x-view-mutation*` corpus exercises. `src`/`q` thread an optional base
		// alias so the alias-qualified body (the alias-qualifier-leak regression
		// shape) is covered. `pk` flags whether the body exposes the base PK as a
		// writable column (needed for a row-identifying predicate).
		interface Shape {
			readonly label: string;
			readonly src: string;
			readonly q: string;
			readonly proj: string;
			readonly pk: boolean;
		}
		const SHAPES: readonly Shape[] = [
			{ label: 'star',     src: 't',      q: '',   proj: '*',                                 pk: true },
			{ label: 'explicit', src: 't',      q: '',   proj: 'id, a, b',                          pk: true },
			{ label: 'rename',   src: 't',      q: '',   proj: 'id as vid, a as va, b as vb',       pk: true },
			{ label: 'computed', src: 't',      q: '',   proj: 'id, a, b + 1 as bp',                pk: true },
			{ label: 'dropkey',  src: 't',      q: '',   proj: 'a, b',                              pk: false },
			{ label: 'alias',    src: 't as x', q: 'x.', proj: 'x.id as aid, x.a as aa, x.b as ab', pk: true },
		];

		/** Build the view-body SQL; `k` (when defined) adds an equality filter on `a`. */
		function buildBody(s: Shape, k: number | undefined): string {
			const where = k === undefined ? '' : ` where ${s.q}a = ${k}`;
			return `select ${s.proj} from ${s.src}${where}`;
		}

		const rowArb = fc.record({
			id: fc.integer({ min: 1, max: 8 }),
			a: fc.integer({ min: 1, max: 3 }),
			b: fc.integer({ min: 1, max: 3 }),
		});
		const filterArb = fc.option(fc.integer({ min: 1, max: 3 }), { nil: undefined });

		async function createBase(): Promise<void> {
			// `a` / `b` are nullable so a computed-column insert (which omits the
			// computed base column) is not a NOT NULL violation — Quereus columns
			// are NOT NULL unless declared `null`.
			await db.exec('create table t (id integer primary key, a integer null, b integer null) using memory');
		}

		/** Replace `t` with the generated rows, deduped by PK; returns the kept rows. */
		async function seedBase(rows: BaseRow[]): Promise<BaseRow[]> {
			await db.exec('delete from t');
			const seen = new Set<number>();
			const kept: BaseRow[] = [];
			for (const r of rows) {
				if (seen.has(r.id)) continue;
				seen.add(r.id);
				await db.exec(`insert into t values (${r.id}, ${r.a}, ${r.b})`);
				kept.push(r);
			}
			return kept;
		}

		async function readBase(): Promise<Record<string, SqlValue>[]> {
			const out: Record<string, SqlValue>[] = [];
			for await (const row of db.eval('select id, a, b from t order by id')) {
				out.push(row as Record<string, SqlValue>);
			}
			return out;
		}

		/** Plan the body standalone and return its top relational node (physical attached). */
		function planBody(body: string): RelationalPlanNode {
			const block = db.getPlan(body) as unknown as { getRelations(): readonly RelationalPlanNode[] };
			return block.getRelations()[0];
		}

		/** The backward view-column model, straight off the shipped lineage surface. */
		function viewModel(body: string): ModelCol[] {
			const sel = new Parser().parse(body) as unknown as AST.SelectStmt;
			const baseTable = db.schemaManager.getTable('main', 't')!;
			return deriveViewColumns(sel, baseTable).map(vc => ({
				name: vc.name,
				base: vc.lineage.kind === 'base' ? vc.lineage.baseColumnName.toLowerCase() : undefined,
			}));
		}

		/** Stable per-cell signature (mirrors Key Soundness `tupleSig`). */
		function cellSig(v: SqlValue): string {
			if (v === null || v === undefined) return 'N';
			if (v instanceof Uint8Array) return 'B:' + Array.from(v).join('.');
			return typeof v + ':' + String(v);
		}

		/** Convert a positional base row to a name-keyed record. */
		function toRecord(r: BaseRow): Record<string, SqlValue> {
			return { id: r.id, a: r.a, b: r.b };
		}

		/**
		 * Positional core shared by PutGet (base post-state vs predicate-honest
		 * oracle) and GetPut (base unchanged): throws when the two row multisets
		 * differ on `cols`. Order-insensitive — compares sorted signatures.
		 */
		function assertRowsEqual(
			label: string,
			actual: readonly Record<string, SqlValue>[],
			expected: readonly Record<string, SqlValue>[],
			cols: readonly string[],
		): void {
			const sig = (rows: readonly Record<string, SqlValue>[]) =>
				rows.map(r => cols.map(c => cellSig(r[c])).join('|')).sort();
			const a = sig(actual);
			const e = sig(expected);
			if (a.length !== e.length || a.some((s, i) => s !== e[i])) {
				throw new Error(`round-trip violation on ${label}: base/image diff\n  expected ${JSON.stringify(e)}\n  actual   ${JSON.stringify(a)}`);
			}
		}

		/**
		 * Pure core of the forward/backward lineage-agreement law. Throws on the
		 * first disagreement between the backward lineage (`model`) and the forward
		 * FD facts (`keys` + `forwardIsSuperkey`):
		 *   (A) every column in a forward key is `base`-writable — a computed
		 *       column in a forward key would have no backward identifying predicate;
		 *   (B) a forward key, traced to base columns plus the filter constants,
		 *       reconstructs the base PK (the row-identifying predicate);
		 *   (C) a base PK that fully survives projection is advertised as a forward
		 *       key — the backward walk's identifying key is not lost forward.
		 */
		function assertLineageAgreement(
			label: string,
			model: readonly ModelCol[],
			basePk: readonly string[],
			filterConstBase: readonly string[],
			keys: readonly (readonly number[])[],
			forwardIsSuperkey: (idx: number[]) => boolean,
		): void {
			for (const key of keys) {
				const baseCols = new Set<string>(filterConstBase);
				for (const i of key) {
					const m = model[i];
					if (!m || m.base === undefined) {
						throw new Error(`lineage disagreement on ${label}: forward key [${key}] includes non-base column '${m?.name ?? i}' (no backward identifying predicate)`);
					}
					baseCols.add(m.base);
				}
				for (const pk of basePk) {
					if (!baseCols.has(pk)) {
						throw new Error(`lineage disagreement on ${label}: forward key [${key}] does not reconstruct base PK column '${pk}'`);
					}
				}
			}

			const survivingPk: number[] = [];
			const covered = new Set<string>();
			model.forEach((m, i) => {
				if (m.base !== undefined && basePk.includes(m.base)) {
					survivingPk.push(i);
					covered.add(m.base);
				}
			});
			const fullySurvives = basePk.length > 0 && basePk.every(pk => covered.has(pk));
			if (fullySurvives && !forwardIsSuperkey(survivingPk)) {
				throw new Error(`lineage disagreement on ${label}: base PK survives projection as [${survivingPk}] but the forward walk does not advertise it as a key`);
			}
		}

		// ----- negative self-tests: each law core reds on an injected violation -----
		it('the round-trip law cores fail loudly on injected violations', () => {
			// PutGet: a base row outside the predicate vanished from the post-state.
			expect(() => assertRowsEqual('injected-widening',
				[{ id: 1, a: 1, b: 1 }],
				[{ id: 1, a: 1, b: 1 }, { id: 2, a: 2, b: 2 }],
				['id', 'a', 'b'],
			)).to.throw(/round-trip violation/);

			// GetPut: a write-back perturbed a base column (spurious diff).
			expect(() => assertRowsEqual('injected-getput',
				[{ id: 1, a: 1, b: 9 }],
				[{ id: 1, a: 1, b: 1 }],
				['id', 'a', 'b'],
			)).to.throw(/round-trip violation/);

			// Lineage (A): a forward key claims a computed column.
			expect(() => assertLineageAgreement('injected-computed-key',
				[{ name: 'id', base: 'id' }, { name: 'bp' }],
				['id'], [], [[1]], () => true,
			)).to.throw(/lineage disagreement/);

			// Lineage (B): a forward key traces to base columns that do not
			// reconstruct the base PK (here the key is `a` only, no `id` and no
			// filter pinning `id`). This is the branch the zoo never reaches on its
			// own (every real forward key traces to `id`), so pin it here.
			expect(() => assertLineageAgreement('injected-unreconstructed-pk',
				[{ name: 'a', base: 'a' }],
				['id'], [], [[0]], () => true,
			)).to.throw(/does not reconstruct base PK/);

			// Lineage (C): the base PK survives but the forward walk lost the key.
			expect(() => assertLineageAgreement('injected-lost-key',
				[{ name: 'id', base: 'id' }, { name: 'a', base: 'a' }],
				['id'], [], [], () => false,
			)).to.throw(/lineage disagreement/);

			// The honest case does not throw.
			expect(() => assertLineageAgreement('honest',
				[{ name: 'id', base: 'id' }, { name: 'a', base: 'a' }],
				['id'], [], [[0]], () => true,
			)).to.not.throw();
		});

		// ----- computed read-only + LIMIT/OFFSET/DISTINCT widening guards -----
		it('computed view columns are read-only, and LIMIT/OFFSET/DISTINCT bodies reject rather than widen', async () => {
			await createBase();
			await db.exec('insert into t values (1, 1, 1), (2, 2, 2), (3, 3, 3)');

			async function expectReject(sql: string, reason: string): Promise<void> {
				let err: unknown;
				try { await db.exec(sql); } catch (e) { err = e; }
				if (err === undefined) throw new Error(`expected '${sql}' to be rejected (${reason}) but it succeeded`);
				const got = (err as { mutationDiagnostic?: { reason?: string } }).mutationDiagnostic?.reason;
				if (got !== undefined) {
					expect(got).to.equal(reason, `wrong diagnostic for '${sql}': ${(err as Error).message}`);
				} else {
					expect((err as Error).message).to.match(/cannot write through view|read-only|non-invertible/i);
				}
			}

			// A computed (non-invertible) column is read-only: a write is rejected
			// with `no-inverse`, not silently dropped.
			await db.exec('create view cv as select id, a, b + 1 as bp from t');
			await expectReject('update cv set bp = 100 where id = 1', 'no-inverse');
			// The base column under it stays writable through the same view.
			await db.exec('update cv set a = 7 where id = 1');
			expect((await readBase()).find(r => r.id === 1)!.a).to.equal(7);

			// LIMIT / OFFSET / DISTINCT bodies are rejected — a mutation would escape
			// the windowed / collapsed view (the write-widening regression made law).
			await db.exec('create view lim_v as select * from t limit 2');
			await expectReject('delete from lim_v where id = 1', 'unsupported-limit');
			await db.exec('create view off_v as select * from t limit 100 offset 1');
			await expectReject('delete from off_v where id = 1', 'unsupported-limit');
			await db.exec('create view dis_v as select distinct a, b from t');
			await expectReject('update dis_v set b = 9 where a = 1', 'unsupported-distinct');
		});

		// ----- Law 1: PutGet (write-then-read) -----
		it('PutGet: a view mutation never escapes the view predicate', async () => {
			await createBase();

			await fc.assert(fc.asyncProperty(
				fc.array(rowArb, { minLength: 0, maxLength: 10 }),
				fc.constantFrom(...SHAPES),
				filterArb,
				fc.constantFrom('insert', 'update', 'delete'),
				fc.integer({ min: 1, max: 8 }),   // id-predicate value
				fc.integer({ min: 1, max: 3 }),   // a-predicate value (key-dropping shape)
				fc.integer({ min: 10, max: 20 }), // update assignment value
				async (rows, shape, k, op, idPred, aPred, nv) => {
					// INSERT needs a writable base PK to mint the new row.
					fc.pre(!(op === 'insert' && !shape.pk));

					const kept = await seedBase(rows);
					const body = buildBody(shape, k);
					await db.exec('drop view if exists v');
					await db.exec(`create view v as ${body}`);

					const model = viewModel(body);
					const writable = model.filter(m => m.base !== undefined);
					const writableNames = writable.map(m => m.name);
					const vis = (av: SqlValue): boolean => k === undefined || av === k;

					/** get(baseAfter): the writable-column image the view should expose. */
					async function assertViewImage(label: string, baseAfter: Record<string, SqlValue>[]): Promise<void> {
						const expected = baseAfter.filter(r => vis(r.a)).map(r => {
							const o: Record<string, SqlValue> = {};
							for (const m of writable) o[m.name] = r[m.base!];
							return o;
						});
						const actual: Record<string, SqlValue>[] = [];
						for await (const row of db.eval(`select ${writableNames.join(', ')} from v`)) {
							actual.push(row as Record<string, SqlValue>);
						}
						assertRowsEqual(`${label} [view image]`, actual, expected, writableNames);
					}

					if (op === 'delete') {
						const pvc = model.find(m => m.base === 'id') ?? model.find(m => m.base === 'a')!;
						const pcol = pvc.base as 'id' | 'a';
						const pval = pcol === 'id' ? idPred : aPred;
						const hit = (r: BaseRow): boolean => r[pcol] === pval && vis(r.a);
						const expected = kept.filter(r => !hit(r)).map(toRecord);
						await db.exec(`delete from v where ${pvc.name} = ${pval}`);
						const after = await readBase();
						assertRowsEqual(`PutGet/delete ${shape.label} k=${k}`, after, expected, ['id', 'a', 'b']);
						await assertViewImage(`PutGet/delete ${shape.label} k=${k}`, after);
					} else if (op === 'update') {
						const pvc = model.find(m => m.base === 'id') ?? model.find(m => m.base === 'a')!;
						const pcol = pvc.base as 'id' | 'a';
						const pval = pcol === 'id' ? idPred : aPred;
						const tvc = model.find(m => m.base !== undefined && m.base !== 'id' && m.name !== pvc.name)!;
						const tBase = tvc.base as 'a' | 'b';
						const hit = (r: BaseRow): boolean => r[pcol] === pval && vis(r.a);
						const expected = kept.map(r => {
							const o = toRecord(r);
							if (hit(r)) o[tBase] = nv;
							return o;
						});
						await db.exec(`update v set ${tvc.name} = ${nv} where ${pvc.name} = ${pval}`);
						const after = await readBase();
						assertRowsEqual(`PutGet/update ${shape.label} k=${k}`, after, expected, ['id', 'a', 'b']);
						await assertViewImage(`PutGet/update ${shape.label} k=${k}`, after);
					} else {
						// insert (pk shapes only — fc.pre filtered the rest)
						const fresh = kept.reduce((mx, r) => Math.max(mx, r.id), 0) + 1;
						const value = (base: string): number => base === 'id' ? fresh : base === 'a' ? (k ?? 1) : 2;
						const vals = writable.map(m => value(m.base!));
						await db.exec(`insert into v (${writableNames.join(', ')}) values (${vals.join(', ')})`);
						const newRow: Record<string, SqlValue> = {
							id: fresh,
							a: writable.some(m => m.base === 'a') ? (k ?? 1) : null,
							b: writable.some(m => m.base === 'b') ? 2 : null,
						};
						const expected = [...kept.map(toRecord), newRow];
						const after = await readBase();
						assertRowsEqual(`PutGet/insert ${shape.label} k=${k}`, after, expected, ['id', 'a', 'b']);
						await assertViewImage(`PutGet/insert ${shape.label} k=${k}`, after);
					}
				},
			), { numRuns: 50 });
		});

		// ----- Law 2: GetPut (read-then-write-back) -----
		it('GetPut: writing read values back through the view leaves the base unchanged', async () => {
			await createBase();
			const pkShapes = SHAPES.filter(s => s.pk);

			await fc.assert(fc.asyncProperty(
				fc.array(rowArb, { minLength: 0, maxLength: 10 }),
				fc.constantFrom(...pkShapes),
				filterArb,
				async (rows, shape, k) => {
					await seedBase(rows);
					const body = buildBody(shape, k);
					await db.exec('drop view if exists v');
					await db.exec(`create view v as ${body}`);

					const model = viewModel(body);
					const pkCol = model.find(m => m.base === 'id')!;
					const writableNonPk = model.filter(m => m.base !== undefined && m.base !== 'id');
					if (writableNonPk.length === 0) return;
					const writableNames = model.filter(m => m.base !== undefined).map(m => m.name);

					const viewRows: Record<string, SqlValue>[] = [];
					for await (const row of db.eval(`select ${writableNames.join(', ')} from v`)) {
						viewRows.push(row as Record<string, SqlValue>);
					}
					fc.pre(viewRows.length > 0);
					const r = viewRows[0];

					const before = await readBase();
					const sets = writableNonPk.map(m => `${m.name} = ${String(r[m.name])}`).join(', ');
					await db.exec(`update v set ${sets} where ${pkCol.name} = ${String(r[pkCol.name])}`);
					const after = await readBase();
					assertRowsEqual(`GetPut ${shape.label} k=${k}`, after, before, ['id', 'a', 'b']);
				},
			), { numRuns: 50 });
		});

		// ----- Law 3: forward/backward lineage agreement (the structural crux) -----
		it('forward/backward lineage agreement holds across the view-body zoo', async () => {
			await createBase();
			const baseTable = db.schemaManager.getTable('main', 't')!;
			const basePk = baseTable.primaryKeyDefinition.map(pk => baseTable.columns[pk.index].name.toLowerCase());

			await fc.assert(fc.asyncProperty(
				fc.constantFrom(...SHAPES),
				filterArb,
				async (shape, k) => {
					const body = buildBody(shape, k);
					const root = planBody(body);
					const cols = root.getType().columns.map(c => c.name);
					const keys = keysOf(root);
					const model = viewModel(body);

					// The forward output and the backward model must be column-aligned
					// positionally: `assertLineageAgreement` feeds model-derived column
					// indices straight into `isUnique` (law C), which reads them as
					// forward-output indices, so a name/order skew between the two
					// surfaces would silently check the wrong columns. Assert exact
					// positional name agreement, not just matching arity.
					if (model.length !== cols.length) {
						throw new Error(`lineage disagreement on ${body}: backward model has ${model.length} columns, forward plan has ${cols.length}`);
					}
					model.forEach((m, i) => {
						if (m.name.toLowerCase() !== cols[i].toLowerCase()) {
							throw new Error(`lineage disagreement on ${body}: backward model column ${i} is '${m.name}' but forward plan column ${i} is '${cols[i]}' (positional skew)`);
						}
					});

					const filterConstBase = k === undefined ? [] : ['a'];
					assertLineageAgreement(body, model, basePk, filterConstBase, keys, idx => isUnique(idx, root));
				},
			), { numRuns: 50 });
		});
	});

});

// Identifier denylist for the declarative-equivalence property arbitrary.
// Kept lightweight (only the lexer keywords the small arbitrary can collide with).
const RESERVED = new Set<string>([
	'select', 'from', 'where', 'and', 'or', 'not', 'null', 'true', 'false',
	'table', 'index', 'view', 'create', 'drop', 'alter', 'rename', 'column',
	'add', 'set', 'primary', 'key', 'unique', 'check', 'default', 'collate',
	'references', 'foreign', 'cascade', 'restrict', 'on', 'delete', 'update',
	'insert', 'into', 'values', 'using', 'with', 'as', 'asc', 'desc',
	'between', 'in', 'exists', 'case', 'when', 'then', 'else', 'end',
	'group', 'by', 'having', 'order', 'limit', 'offset', 'distinct', 'all',
	'inner', 'left', 'right', 'full', 'outer', 'cross', 'join', 'union',
	'intersect', 'except', 'diff', 'cast', 'is', 'like', 'glob', 'match',
	'regexp', 'begin', 'commit', 'rollback', 'savepoint', 'release',
	'pragma', 'analyze', 'temp', 'temporary', 'if', 'integer', 'real', 'text',
	'blob', 'numeric', 'declare', 'schema', 'version', 'apply', 'explain',
	'seed', 'assertion', 'constraint', 'generated', 'always', 'stored', 'virtual',
	'context', 'tags', 'nulls', 'first', 'last', 'rows', 'range', 'over',
	'partition', 'preceding', 'following', 'unbounded', 'current', 'row',
	'returning', 'option', 'maxrecursion', 'lateral', 'recursive', 'no', 'action',
	'conflict', 'abort', 'fail', 'ignore', 'replace', 'deferrable',
	'initially', 'deferred', 'immediate',
	'count', 'sum', 'avg', 'min', 'max', 'length', 'substr', 'abs',
]);
